:PROPERTIES:
:ID:       097dda02-a6dc-4adc-928e-96d2b35ef673
:ROAM_ALIASES: Lockhart-08
:END:
#+title: El lamento de un matemático
#+filetags: :#Matemáticas:#Enseñanza:

[[http://funes.uniandes.edu.co/8476/][El lamento de un matemático]] de Paul Lockhart.

El original es 

+ Lo primero que hay que entender es que las matemáticas son un arte.

+ "Un matemático, como un pintor o un poeta, es un creador de patrones.
  Si sus patrones son más permanentes que los del poeta, es porque están
  hechos de ideas." de Hardy  

+ Si hay algo parecido a un principio estético unificador en las
  matemáticas, es simplemente esto: /la simplicidad es bella/.

+ Eliminando el proceso creativo y dejando sólo los resultados del
  proceso, casi se garantiza que nadie vaya a tener atracción a la
  asignatura.

+ Concentrándose en el /qué/ y omitiendo el /por qué/, las matemáticas
  se reducen a una cáscara vacía. El arte no está en la «verdad» sino en
  la explicación, el argumento.  Es el argumento en sí el que da a la
  verdad su contexto, y determina qué es lo que realmente se está
  diciendo, así como su significado. Las matemáticas son el /arte de la
  explicación/.

+ No estoy protestando por la presencia de hechos y fórmulas en las
  clases de matemáticas, estoy protestando por la falta de /matemáticas/
  en las clases de matemáticas.

+ En ningún momento se revela el secreto a los alumnos de que las
  matemáticas, al igual que cualquier literatura, es creada por los
  seres humanos para su propia diversión; que las obras de matemáticas
  están sujetas a evaluación crítica; que uno puede tener y desarrollar
  /gusto/ matemático. Una pieza de matemáticas es como un poema, y
  podemos preguntarnos si satisface nuestros criterios estéticos: ¿Es
  lógico el argumento? ¿Tiene sentido? ¿Es simple y elegante? ¿Me acerca
  al quid de la cuestión?

+ El problema es que las matemáticas, como la pintura o la poesía, son
  un trabajo creativo duro. Eso las hace muy difíciles de enseñar. Las
  matemáticas son un proceso lento y contemplativo.

+ Las matemáticas son un /arte/, y el arte debería ser enseñado por
  artistas, y si no, al menos por gente que aprecia esa forma de arte y
  la reconoce cuando la ve.

+ Lo realmente doloroso de cómo se enseñan las matemáticas en el colegio no es
  lo que falta —el hecho de que no se están haciendo matemáticas de verdad en las
  clases de matemáticas— sino lo que hay en su lugar: el montón de desinformación
  destructiva conocida como «el currículo de matemáticas».

+ Las matemáticas tratan de problemas, y los problemas tienen que
  hacerse el foco de la vida matemática de un estudiante.

+ Lo que está sucediendo es el debilitamiento sistemático de la
  intuición de los estudiantes. Una demostración, esto es, un argumento
  matemático, es una obra de ficción, un poema. Su objetivo es
  /satisfacer/. Una demostración bonita debería expli- car, y debería
  explicar clara, profunda y elegantemente. Un argumento bien escrito y
  bien confeccionado debería sentirse como un jarro de agua fría, y ser
  un faro que ilumine —debería refrescar el espíritu e iluminar la
  mente—. Y debería ser /cautivador/.

+ Hay un lugar para las demostraciones formales en las matemáticas, sin
  duda. Pero ese lugar no es la primera introducción que tiene un
  estudiante a la argumentación matemática.

+ La demostración rigurosa y formal sólo se convierte en importante
  cuando hay una /crisis/ —cuando te das cuenta de que tu objeto
  imaginario se comporta de forma anti-intuitiva; cuando hay una
  paradoja de algún tipo—.

+ El problema con el currículo estándar de geometría es que la
  experiencia personal de ser un artista que se esfuerza ha sido
  prácticamente eliminada. El arte de la demostración se ha reemplazado
  por un rígido patrón de deducciones formales sin inspiración.

+ Se les enseña a imitar argumentos, no a intentar hacerlos. Así que no
  sólo no tienen ni idea de qué está diciendo su profesor, no tienen ni
  idea de qué están diciendo ellos mismos.

  
