:PROPERTIES:
:ID:       536558a7-c306-40b8-87ac-94f50c414060
:ROAM_ALIASES: Sanchez+Gil-15
:END:
#+title: La demostración en las matemáticas. Un ejemplo de aplicación en el aula con alumnos de 3.º ESO
#+filetags: :#Matemáticas:#Bachillerato:

[[https://bit.ly/3O8NsSS][La demostración en las matemáticas. Un ejemplo de aplicación en el
aula con alumnos de 3.º ESO]] de Enrique Sánchez Freire y Juan Antonio Gil
Pascual. 

En el artículo se muestra la influencia que han tenido el rigor y sus
respectivos procedimientos en diferentes momentos de la Historia de las
Matemáticas y como algunas demostraciones y problemas han jugado un
papel importantísimo en el desarrollo de las Matemáticas.

Se complementa con los resultados de una experiencia de aula en donde
comprobaremos que un grupo en donde se aplicó una metodología en la cual
los procesos de argumentación y demostración tuvieron una especial
relevancia obtuvo mejores resultados en unas pruebas de resolución de
problemas que otro grupo del mismo nivel al que se le aplicó una
metodología más tradicional.
